### ISSUE TITLE
Not able to run the TRPO example on GPU

### ISSUE THREAD

**Issue by avijit9** [Khrylx/PyTorch-RL#12]
How to run the TRPO example on GPU? I am getting an error at this: https://github.com/Khrylx/PyTorch-RL/blob/master/core/trpo.py#L83

**Comment by Khrylx** [comment]
What error did you get? Is it this one https://github.com/Khrylx/PyTorch-RL/issues/1#issue-282815581?
One solution would be upgrade your CUDA version to 9.0.
