### ISSUE TITLE
question about weight init

### ISSUE THREAD

**Issue by gunshi** [Khrylx/PyTorch-RL#14]
Hi,
Your implementation is great and easy to read.
I just had one question though, from the line:
https://github.com/Khrylx/PyTorch-RL/blob/15b574f5d52f5eeab6917c90c17e8739578f3d96/models/mlp_policy.py#L24
Is there any particular reason why the weights are initialized like that(instead of the normal gaussian/xavier's scheme) with that specific scale?
Thanks!
Gunshi

**Comment by Khrylx** [comment]
Hi,

This is just a choice inherited from other reference implementation. I find it working well in practice, although better initialization could yield better results for some problems.

Ye

**Comment by gunshi** [comment]
Thanks for the answer!
