### ISSUE TITLE
GAIL discriminator loss uses complete expert data in each iteration? 

### ISSUE THREAD

**Issue by SapanaChaudhary** [Khrylx/PyTorch-RL#18]
https://github.com/Khrylx/PyTorch-RL/blob/f44b4444c9db5c1562c5d0bc04080c319ba9141a/gail/gail_gym.py#L126

The number of generator data samples seems to be around 2088, while the number of expert samples is 50000. Shouldn't the number of expert samples be the same as that of generator's?

**Comment by Khrylx** [comment]
The BCELoss we use for the discriminator will divide the loss by the number of samples. So it should be fine.

**Comment by SapanaChaudhary** [comment]
That is right. So, the whole of expert data is used in each iteration. Is that fair? If I were to sample the same number of data samples (from complete pool of expert data) as that of generator's, how would you suggest I sample (uniformly random)?

**Comment by Khrylx** [comment]
Yes, maybe randomly sample a batch of expert data.

**Comment by SapanaChaudhary** [comment]
Okay. Thank you.
