### ISSUE TITLE
Doubt regarding the calculation of advantage

### ISSUE THREAD

**Issue by nesarasr** [Khrylx/PyTorch-RL#23]
Hey, thanks for this great repository! I am a beginner in RL and I am trying to understand the practical implementation of TRPO.
What is the purpose of multiplying the variable 'mask' while computing advantage (in estimate_advantage() function)?
And what range of values do 'masks' take?

Thanks!

**Comment by Khrylx** [comment]
Since we are concatenating all episodes together inside the batch, mask is to make sure that rewards from previous episodes are not added to the current episode.

**Comment by nesarasr** [comment]
Got it, thank you!!
