### ISSUE TITLE
Autograd Import Error

### ISSUE THREAD

**Issue by aseembits93** [Khrylx/PyTorch-RL#3]
Hi @Khrylx !
I'm trying your code out of the box by running `python examples/ppo_gym.py --env-name Hopper-v1`
I get the following error - 

> Traceback (most recent call last):
  File "examples/ppo_gym.py", line 9, in <module>
    from utils import *
  File "/home/aseem/treeqn_atreec/PyTorch-RL/utils/__init__.py", line 3, in <module>
    from utils.torch import *
  File "/home/aseem/treeqn_atreec/PyTorch-RL/utils/torch.py", line 3, in <module>
    from torch.autograd import Variable
ImportError: No module named autograd

Could you help me out with it? I suspect there is an issue with setting up PYTHONPATH variable correctly.

**Comment by Khrylx** [comment]
Are you using python 3.5? I haven't seen this error before.

**Comment by aseembits93** [comment]
oh, I'm using 2.7 actually

**Comment by Khrylx** [comment]
Then you should use python3.5.
