### ISSUE TITLE
result is not good

### ISSUE THREAD

**Issue by Terrywjx** [Khrylx/PyTorch-RL#7]
hi, thank you for your sharing. But I have a question, why I cannot get good result in mujoco environment, do you have any idea?

**Comment by Khrylx** [comment]
Hi there,

Could you please paste the commands you run and the results after 1000 iterations? The term “not good” is pretty vague, and I don’t know how to debug this issue.

**Comment by Terrywjx** [comment]
Yes，the result is good, sorry for delayed reply. Thanks very much
