### ISSUE TITLE
Entropy Term for GAIL

### ISSUE THREAD

**Issue by sanvenDev** [Khrylx/PyTorch-RL#9]
In the paper https://arxiv.org/pdf/1606.03476.pdf, (Jonathan Ho GAIL's paper), there is a Causal Entropy term for Policy network update step. I could not find any where in your code, anything related to that entropy. Did you skip the entropy term? Would it not completely change the objective function, the whole derivation depended on Maximum Causal Entropy IRL, which just became a kind of regularizer at the end.

I think if Causal Entropy term is included, then instead of maximum entropy IRL you are doing something else implicitly, which may be wrong/suboptimal? Correct me if I'm wrong.

**Comment by Khrylx** [comment]
Thank you for pointing out this. In my implementation, I just set the regularizer coefficient lambda to zero. The paper actually compared different lambda including zero. I might later try to add this term, though I find current performance is okay.

**Comment by sanvenDev** [comment]
Ok, I just now noticed the paper's performance when coefficient is zero. Thanks for clearing this out.
